/**
 * SVG Export — Generate fabrication-ready SVG with slot cutout paths
 *
 * Units are in millimeters for CNC/laser cutting compatibility.
 */

import type { Slot } from '../algorithms/perforation';

export interface SvgExportOptions {
	panelWidth: number;   // mm
	panelHeight: number;  // mm
	slots: Slot[];
	includePanel: boolean;
}

/**
 * Generate an SVG string from slot data.
 */
export function generateSvg(options: SvgExportOptions): string {
	const { panelWidth, panelHeight, slots, includePanel } = options;

	const lines: string[] = [];

	lines.push(`<?xml version="1.0" encoding="UTF-8"?>`);
	lines.push(`<svg xmlns="http://www.w3.org/2000/svg" width="${panelWidth}mm" height="${panelHeight}mm" viewBox="0 0 ${panelWidth} ${panelHeight}">`);
	lines.push(`  <title>ImageLines Perforated Panel</title>`);
	lines.push(`  <desc>Generated by ImageLines Playground — ${slots.length} perforations</desc>`);

	if (includePanel) {
		lines.push(`  <rect x="0" y="0" width="${panelWidth}" height="${panelHeight}" fill="#cccccc" stroke="#333333" stroke-width="0.5"/>`);
	}

	lines.push(`  <g id="perforations" fill="#000000" stroke="none">`);

	for (const slot of slots) {
		const cx = slot.x * panelWidth;
		const cy = slot.y * panelHeight;
		const w = slot.length;
		const h = slot.width;
		const deg = (slot.rotation * 180) / Math.PI;

		// Position rect centered at (cx, cy) with rotation
		lines.push(`    <rect x="${(cx - w / 2).toFixed(3)}" y="${(cy - h / 2).toFixed(3)}" width="${w.toFixed(3)}" height="${h.toFixed(3)}" rx="0.5" transform="rotate(${deg.toFixed(2)} ${cx.toFixed(3)} ${cy.toFixed(3)})"/>`);
	}

	lines.push(`  </g>`);
	lines.push(`</svg>`);

	return lines.join('\n');
}

/**
 * Download SVG as a file.
 */
export function downloadSvg(svgContent: string, filename: string = 'imagelines-panel.svg') {
	const blob = new Blob([svgContent], { type: 'image/svg+xml' });
	const url = URL.createObjectURL(blob);
	const a = document.createElement('a');
	a.href = url;
	a.download = filename;
	a.click();
	URL.revokeObjectURL(url);
}
